name: Release Please

permissions:
  id-token: write
  contents: write
  pull-requests: write
  packages: read
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
      - name: Echo JSON Output
        run: echo '${{ toJson(steps.release.outputs) }}'
